# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.


- id: fuel-plugin-git-deployment-puppet
  type: puppet
  version: 2.0.0
  role: ['primary_controller', 'controller', 'compute', 'cinder', 'base-os']
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "manifests/git.pp"
    puppet_modules: "modules"
    timeout: 180

#- id: test-post-deployment-sh
#  type: shell
#  role: [test_role]
#  version: 2.0.0
#  cross-depends:
#    - name: post_deployment_start
#  cross-depended-by:
#    - name: post_deployment_end
# #  requires: [post_deployment_start]
# #  required_for: [post_deployment_end]
#  parameters:
#    cmd: echo post_deployment_task_executed > /tmp/post_deployment
#    retries: 3
#    interval: 20
#    timeout: 180

#- id: test-pre-deployment-sh
#  type: shell
#  role: [test_role]
#  version: 2.0.0
#  cross-depends:
#    - name: pre_deployment_start
#  cross-depended-by:
#    - name: pre_deployment_end
# #  requires: [pre_deployment_start]
# #  required_for: [pre_deployment_end]
#  parameters:
#    cmd: echo pre_deployment_task_executed > /tmp/pre_deployment
#    retries: 3
#    interval: 20
#    timeout: 180
